---
title: "basic-usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basic-usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library('GenoClustR')
devtools::load_all()
library('rlang')
library('ggplot2')
library("Hmisc")
library('gplots')
library("WGCNA")
enableWGCNAThreads()
```


```{r}
# Load your input file containing expression data under the name "MyData"
sclero_test <- sclero
#save(sclero_test, file = "../tests/testthat/data/sclero_test.rda")
# Load your input file containing ordered list of genes on contig
MyGeneNames <- rownames(sclero_test)



# Name your analysis by typing in:
AnalysisName <- "MyAnalysis"

#save(sclero_test_corr, file = "../tests/testthat/data/sclero_test_corr.rda")
#save(sclero_test_ave_corr, file = "../tests/testthat/data/sclero_test_ave_corr.rda")
```

```{r}
raw <- two_overlapping_gappy_clusters(seed = 123)
raw_cov <- raw$covariance #/ 2
diag(raw_cov) <- 1
raw <- raw$features
#raw_cov <- gene_corr(sclero_test)
```

```{r}
threshold_clustering <- function(
  adjacency,
  threshold = 0.8,
  edge_fill_rate = 0.8,
  surface_fill_rate = 0.6,
  gap_penalty = 0.5,
  min_cluster = 4,
  max_cluster = NULL,
  smooth = "average",
  merge = TRUE,
  merge_threshold = 1.1,
  verbose = FALSE
) {
  # We want to avoid mutating anything.
  adjacency <- adjacency
  
  if (verbose && (smooth %in% c("average", "TOM"))) {
    print(sprintf("- Running %s smoothing", smooth))
  }
  if (smooth == "average") {
    smoothed <- average_corr(adjacency, bandwidth = max_cluster)
  } else if (smooth == "TOM") {
    smoothed <- TOMsimilarity(adjacency)
  } else {
    smoothed <- adjacency
  }
  
  adjacency[lower.tri(adjacency)] <- NA
  smoothed[lower.tri(smoothed)] <- NA
  
  smoothed <- threshold_matrix(smoothed, threshold = threshold)
  
  if (verbose) {
    print("- Finding edges")
  }
  edge_mins <- find_edges(smoothed, bandwidth = max_cluster)
  
  if (verbose) {
    print("- Finding surface means")
  }
  surface_means <- average_corr(smoothed, bandwidth = max_cluster)
  gaps <- find_gaps(smoothed)
  
  if (verbose) {
    print("- Finding clusters")
  }
  clusters1 <- find_threshold_clusters(
    adjacency = adjacency, 
    edge_mins = edge_mins,
    surface_means = surface_means,
    gaps = gaps,
    edge_fill_rate = edge_fill_rate,
    gap_penalty = gap_penalty,
    surface_fill_rate = surface_fill_rate,
    min_cluster = min_cluster,
    max_cluster = max_cluster
  )
  
  if (merge) {
    if (verbose) {
      print("- Merging clusters")
    }
    clusters2 <- merge_threshold_clusters(
      clusters = clusters1,
      adjacency = adjacency,
      surface_means = surface_means,
      edge_mins = edge_mins,
      gaps = gaps,
      merge_threshold = merge_threshold
    )
  }
 
  out <- list(
    clusters = clusters2,
    smoothed = smoothed,
    surface_means = surface_means,
    edge_mins = edge_mins
  )
  return(out)
}

out <- threshold_clustering(1 * (raw_cov > 0.7), min_cluster = 4, max_cluster = 50)
out$clusters
out$init_clusters
```

```{r}
plotit <- function(li) {
  heatmap(li$covariance, Rowv = NA, Colv = NA, symm = TRUE)
  heatmap(cor(li$features), Rowv = NA, Colv = NA, symm = TRUE)
  print(quantile(cor(li$features)))
}

#plotit(no_clusters(seed = 14))
#s <- c(1, 2, 3, 14)

#plotit(one_cluster(seed = 27))
#s <- c(17, 19, 22, 27)

#plotit(two_clusters(seed = 31))
#s <- c(28, 29, 30, 31)

#plotit(five_clusters(seed = 38))
#s <- c(33, 35, 37, 38)

#plotit(two_covarying_clusters(seed = 42))
#s <- c(39, 40, 41, 42)

#plotit(five_covarying_clusters(seed = 48))
#s <- c(44, 46, 46, 48)

#plotit(one_gappy_cluster(seed = 56))
#s <- c(50, 51, 52, 56)

#plotit(two_gappy_clusters(seed = 60))
#s <- c(57, 58, 59, 60)

#plotit(five_gappy_clusters(seed = 68))
#s <- c(64, 66, 67, 68)

#plotit(one_noisy_cluster(seed = 83))
#s <- c(74, 81, 82, 83)

#plotit(two_noisy_clusters(seed = 107))
#s <- c(92, 94, 100, 107)

#plotit(five_noisy_clusters(seed = 123))
#s <- c(116, 120, 121, 123)

```




